name: Deploy
on:
  workflow_call:


jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get short sha
        run : IMAGE_TAG_SHA="${{ github.sha }}" && IMAGE_TAG_SHORT_SHA="${IMAGE_TAG_SHA:0:6}" && echo $IMAGE_TAG_SHORT_SHA

      - name: login
        run: make login --environment-overrides GHCR_TOKEN=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  USER_NAME=fargus3222

      - name: build
        run: make build --environment-overrides IMAGE_NAME=${{ github.event.repository.name }}
        
      - name: build
        run: make tag --environment-overrides IMAGE_NAME=${{ github.event.repository.name }} IMAGE_TAG=$(IMAGE_TAG_SHORT_SHA)

      - name: push
        run: make push --environment-overrides IMAGE_NAME=${{ github.event.repository.name }} IMAGE_TAG=$(IMAGE_TAG_SHORT_SHA)