name: Deploy
on:
  workflow_call:


jobs:


  Get_short_sha:
    runs-on: self-hosted

    outputs:
      image_tag: ${{ steps.sha.outputs.image_tag }}

    steps:
      - uses: actions/checkout@v4

      - name: Get short sha
        id: sha
        run: |
          echo "image_tag=${GITHUB_SHA:0:7}" >> $GITHUB_OUTPUT


  build:
    needs: Get_short_sha
    runs-on: self-hosted
    environment: CD
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: login
        run: make login --environment-overrides GHCR_TOKEN=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  USER_NAME=fargus3222

      - name: pull cache
        run: docker pull ghcr.io/homelabfargus/${{ github.event.repository.name }}:latest

      - name: build
        run: make build --environment-overrides IMAGE_NAME=${{ github.event.repository.name }} IMAGE_TAG=${{ needs.Get_short_sha.outputs.image_tag }}

      - name: push_tag
        run: make push_tag --environment-overrides IMAGE_NAME=${{ github.event.repository.name }} IMAGE_TAG=${{ needs.Get_short_sha.outputs.image_tag }}

      - name: push_latest
        run: make push_latest --environment-overrides IMAGE_NAME=${{ github.event.repository.name }} IMAGE_TAG=${{ needs.Get_short_sha.outputs.image_tag }}

  cd:
    needs: [Get_short_sha, build]
    runs-on: self-hosted
    if: ${{ env.IS_DEPLOYDED == 'true' }}
    environment: CD
    steps:
      - name: cd
        run: make cd --environment-overrides GITHUB_TOKEN=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 MANIFEST_PATH_CI=${{ vars.MANIFEST_PATH }} CONTAINER_NAME=${{ vars.CONTAINER_NAME }} IMAGE_NAME=${{ github.event.repository.name }} IMAGE_TAG=${{ needs.Get_short_sha.outputs.image_tag }}